/**
 * PDF report builder — uses pdf-lib (pure JS, no external services).
 * Pure server-side; the Node SSR adapter ships the bytes back to the browser.
 */

import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import type { ResearchReport } from './research-graph';

const MARGIN = 56;
const PAGE_WIDTH = 612;   // US Letter width in points
const PAGE_HEIGHT = 792;  // US Letter height in points

// Match the portfolio's "agent green" so the PDF feels on-brand
const ACCENT = rgb(0.13, 0.77, 0.37);
const TEXT = rgb(0.13, 0.13, 0.13);
const MUTED = rgb(0.45, 0.45, 0.45);
const RULE = rgb(0.85, 0.85, 0.85);

export async function buildReportPdf(report: ResearchReport): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const sans = await pdf.embedFont(StandardFonts.Helvetica);
  const sansBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const mono = await pdf.embedFont(StandardFonts.Courier);

  let page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - MARGIN;

  const newPage = () => {
    page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    y = PAGE_HEIGHT - MARGIN;
  };

  const drawText = (text: string, opts: { font?: typeof sans; size?: number; color?: typeof TEXT; gap?: number } = {}) => {
    const font = opts.font ?? sans;
    const size = opts.size ?? 11;
    const color = opts.color ?? TEXT;
    const gap = opts.gap ?? 4;

    // Wrap by width
    const maxWidth = PAGE_WIDTH - MARGIN * 2;
    const words = text.split(/\s+/);
    let line = '';
    const lines: string[] = [];

    for (const word of words) {
      const candidate = line ? `${line} ${word}` : word;
      const w = font.widthOfTextAtSize(candidate, size);
      if (w > maxWidth && line) {
        lines.push(line);
        line = word;
      } else {
        line = candidate;
      }
    }
    if (line) lines.push(line);

    for (const ln of lines) {
      if (y < MARGIN + size + 10) newPage();
      page.drawText(ln, { x: MARGIN, y, size, font, color });
      y -= size + gap;
    }
  };

  const rule = () => {
    if (y < MARGIN + 20) newPage();
    page.drawLine({
      start: { x: MARGIN, y },
      end: { x: PAGE_WIDTH - MARGIN, y },
      thickness: 0.5,
      color: RULE,
    });
    y -= 14;
  };

  /* ── Header ──────────────────────────────────────────── */
  page.drawRectangle({
    x: 0, y: PAGE_HEIGHT - 6, width: PAGE_WIDTH, height: 6,
    color: ACCENT,
  });

  drawText('DEEP RESEARCH REPORT', { font: mono, size: 9, color: ACCENT, gap: 2 });
  y -= 4;
  drawText(report.topic, { font: sansBold, size: 22, gap: 4 });
  drawText(
    `Generated ${new Date(report.generatedAt).toUTCString()}  ·  Report ID: ${report.id}`,
    { font: mono, size: 8, color: MUTED, gap: 14 },
  );
  rule();

  /* ── Metadata strip ──────────────────────────────────── */
  const metaY = y;
  const colW = (PAGE_WIDTH - MARGIN * 2) / 3;
  const drawMetric = (label: string, value: string, col: number) => {
    const x = MARGIN + col * colW;
    page.drawText(label, { x, y: metaY, size: 8, font: mono, color: MUTED });
    page.drawText(value, { x, y: metaY - 13, size: 13, font: sansBold, color: TEXT });
  };
  drawMetric('COST', `$${report.cost.usd.toFixed(3)}`, 0);
  drawMetric('TOKENS', report.cost.tokens.toLocaleString(), 1);
  drawMetric('DURATION', `${(report.durationMs / 1000).toFixed(1)}s`, 2);
  y = metaY - 30;
  rule();

  /* ── Sub-questions ───────────────────────────────────── */
  drawText('Research Plan', { font: sansBold, size: 13, gap: 8 });
  for (const q of report.subQuestions) {
    drawText(`•  ${q}`, { size: 10, gap: 4 });
  }
  y -= 10;

  /* ── Summary ─────────────────────────────────────────── */
  drawText('Executive Summary', { font: sansBold, size: 13, gap: 8 });
  // Strip markdown headings/bold for the PDF body — keep it plain
  const cleanSummary = report.summary
    .replace(/^##+\s*/gm, '')
    .replace(/\*\*/g, '')
    .replace(/^_+|_+$/g, '');

  for (const para of cleanSummary.split('\n\n')) {
    const line = para.trim();
    if (!line) continue;
    if (line.startsWith('### ')) {
      drawText(line.replace(/^###\s*/, ''), { font: sansBold, size: 11, gap: 6 });
    } else {
      drawText(line, { size: 10, gap: 4 });
    }
    y -= 4;
  }

  /* ── Sources ─────────────────────────────────────────── */
  if (y < 200) newPage();
  rule();
  drawText('Sources', { font: sansBold, size: 13, gap: 8 });
  for (const [i, s] of report.sources.entries()) {
    drawText(`[${i + 1}] ${s.title}`, { font: sansBold, size: 10, gap: 3 });
    drawText(s.citation, { font: mono, size: 8, color: MUTED, gap: 3 });
    drawText(s.finding, { size: 9, gap: 8 });
  }

  /* ── Footer (last page) ──────────────────────────────── */
  page.drawText(
    'Generated by the Deep Research Agent · tvabraham.dev',
    { x: MARGIN, y: 30, size: 7, font: mono, color: MUTED },
  );

  return pdf.save();
}
